services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    command:
      - --ssl-ca=/etc/mysql/certs/ca.pem
      - --ssl-cert=/etc/mysql/certs/server-cert.pem
      - --ssl-key=/etc/mysql/certs/server-key.pem
      - --ssl=1
      - --bind-address=0.0.0.0
      - --require_secure_transport=ON
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./certs:/etc/mysql/certs:ro

volumes:
  mysql_data:
